update scripts

diff --git a/bin/pip-upgrade b/bin/pip-upgrade
--- a/bin/pip-upgrade
+++ b/bin/pip-upgrade
@@ -13,7 +13,19 @@ no_update=(
 test "$1" = '-2' && pyversion=2
 test "$1" = '-3' && pyversion=3
 
-python_pip="python$pyversion -m pip"
+python_cmd=python$pyversion
+
+if ! command -v $python_cmd >/dev/null; then
+  echo "Python executable '$python_cmd' could not be found, skipping pip package upgrades"
+  exit
+fi
+
+if ! $python_cmd -m pip --version >/dev/null 2>&1; then
+  echo "Pip module is not installed, skipping pip package upgrades"
+  exit
+fi
+
+python_pip="$python_cmd -m pip"
 
 no_grep="$(echo "${no_update[@]}" | awk 'gsub(/[[:space:]]+/, "|")')"
 
